wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 4
LEARNING_RATE_MULTIPLIER:
  desc: null
  value: 0.1
MODEL:
  desc: null
  value: curie
N_EPOCHS:
  desc: null
  value: 4
PROMPT_LOSS_WEIGHT:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1656447644
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.19
      8:
      - 3
      - 5
